"""store schema

Revision ID: 7ab73a6dc264
Revises: 
Create Date: 2026-08-25 07:33:58.589924
"""
from alembic import op
import sqlalchemy as sa


revision = '7ab73a6dc264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_at', 'audit_logs', ['created_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('card_uid', sa.String(length=64), nullable=True),
    sa.Column('employee_type', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_employee_active_card', 'employees', ['card_uid'], unique=True, postgresql_where=sa.text('is_active AND card_uid IS NOT NULL'))
    op.create_table('schedule_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('image_mime', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('tiles', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', name='uq_schedule_week')
    )
    op.create_table('shift_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('card_uid', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('tapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_event_id', name='uq_punch_client_event')
    )
    op.create_index('ix_punch_emp_tapped', 'punch_events', ['employee_id', 'tapped_at'], unique=False)
    op.create_index('ix_punch_tapped_at', 'punch_events', ['tapped_at'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['schedule_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sched_entry_date', 'schedule_entries', ['work_date'], unique=False)
    op.create_table('schedule_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['schedule_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_punch_id', sa.Integer(), nullable=True),
    sa.Column('check_out_punch_id', sa.Integer(), nullable=True),
    sa.Column('ignored_punch_ids', sa.JSON(), nullable=False),
    sa.Column('is_adjusted', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_bdate', 'work_sessions', ['business_date'], unique=False)
    op.create_index('ix_session_emp_bdate', 'work_sessions', ['employee_id', 'business_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_emp_bdate', table_name='work_sessions')
    op.drop_index('ix_session_bdate', table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_table('schedule_revisions')
    op.drop_index('ix_sched_entry_date', table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index('ix_punch_tapped_at', table_name='punch_events')
    op.drop_index('ix_punch_emp_tapped', table_name='punch_events')
    op.drop_table('punch_events')
    op.drop_table('adjustments')
    op.drop_table('shift_presets')
    op.drop_table('schedule_weeks')
    op.drop_table('schedule_imports')
    op.drop_index('uq_employee_active_card', table_name='employees', postgresql_where=sa.text('is_active AND card_uid IS NOT NULL'))
    op.drop_table('employees')
    op.drop_index('ix_audit_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
